# Generated by Django 5.1.1 on 2024-11-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='CODE')),
                ('name', models.CharField(max_length=50, verbose_name='Vendor Fantasy Name')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('holder_name', models.CharField(max_length=50, verbose_name="Holder's Name")),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('vendor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendortype')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=8, verbose_name='Payment Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('due_date', models.DateField(null=True)),
                ('has_impacted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vendor', 'payment_number'), name='unique vendorcodepayment')],
            },
        ),
    ]
