services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ecashflow@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  django-app:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ecashflow.rule=Host(`ecashflow.online`)"
      - "traefik.http.routers.ecashflow.entrypoints=websecure"
      - "traefik.http.routers.ecashflow.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
      build: .
      command: bash -c "python manage.py migrate && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
#      deploy:
#        mode: replicated
#        replicas: 3
      restart: always
      env_file: ".env"
volumes:
  letsencrypt: