NUMERO_DE_SUCURSAL_ECASHFLOW: str = "4572"
NUMERO_DE_SUCURSAL_BANCO: str = "4623"

NUMERO_DE_ENTIDAD_VIRTUAL: str = "000"
NUMERO_DE_ENTIDAD_BANCARIA: str = "011"

NOMBRE_BANCO_ECASHFLOW: str = "ECashFlow"
NOMBRE_BANCO_FICTICIO: str = "Banco Colomar SA"

