# Generated by Django 5.1.1 on 2024-11-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('validation_token', models.CharField(default='token', max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funds_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marital_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(default='last_name', max_length=30, verbose_name='Apellido')),
                ('full_name', models.CharField(default='full_name', max_length=60, verbose_name='Nombre Completo')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número de Teléfono')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('isPEP', models.BooleanField(default=False, verbose_name='Es Persona Politicamente Expuesta')),
                ('isLB', models.BooleanField(default=False, verbose_name='Es Sujeto Obligado')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer_type')),
                ('funds_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.funds_source')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.marital_status')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profession')),
                ('tax_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tax_situation')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDataChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('field_value', models.CharField(max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_token', models.CharField(default='token', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
